version: "3.8"
services:
  backend:
    build: ../../build/
    ports:
      - "5000:5000"
    links:
      - mysql
  mysql:
    image: mariadb:10.7-focal
    ports:
      - "3306:3306"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PASSWORD: dbpass
      MYSQL_USER: dbuser
      MYSQL_DATABASE: ods